anexos/urls.py
from django.urls import path
from . import views

app_name = 'anexos'

urlpatterns = []

urlpatterns += (
    # path('pasta/', views.PastaListView.as_view(), name='pasta_anexo_list'),
    # path('pasta/create/', views.PastaCreateView.as_view(), name='pasta_anexo_create'),
    path('pasta/delete/<int:pk>/', views.PastaDeleteView.as_view(), name='pasta_anexo_delete'),
    # path('pasta/detail/<int:pk>/', views.PastaDetailView.as_view(), name='pasta_anexo_detail'),
    path('pasta/', views.PastaUpdateView.as_view(), name='pasta_anexo_update'),
)

urlpatterns += (
    path('', views.AnexoListView.as_view(), name='anexo_list'),
    path('filter/<str:filter>/', views.AnexoListView.as_view(), name='anexo_filter'),
    path('pasta/<int:pastaId>/', views.AnexoListView.as_view(), name='anexo_pasta'),
    path('create/', views.AnexoCreateView.as_view(), name='anexo_create'),
    path('detail/<int:pk>/', views.AnexoDetailView.as_view(), name='anexo_detail'),
    path('update/<int:pk>/', views.AnexoUpdateView.as_view(), name='anexo_update'),
    path('rest/update/', views.AnexoRestUpdateView.as_view(), name="anexo_rest_update"),
    path('delete/ajax/<int:pk>/', views.AnexoDeleteAjaxView.as_view(), name='anexo_delete_ajax'),
    path('delete/<int:pk>/', views.AnexoDeleteView.as_view(), name='anexo_delete'),
)

urlpatterns += (
    # urls for AnexoRecipiente
    path('<int:related_type>/<int:related_id>', views.AnexoRecipienteListView.as_view(), name='anexorecipiente_list'),
    path('<int:related_type>/<int:related_id>/create/', views.AnexoRecipienteCreateView.as_view(), name='anexorecipiente_create'),
    path('<int:related_type>/<int:related_id>/detail/<int:pk>/', views.AnexoRecipienteDetailView.as_view(),
         name='anexorecipiente_detail'),
    path('<int:related_type>/<int:related_id>/update/<int:pk>/', views.AnexoRecipienteUpdateView.as_view(),
         name='anexorecipiente_update'),
    path('<int:related_type>/<int:related_id>/delete/<int:pk>/', views.AnexoRecipienteDeleteView.as_view(),
         name='anexorecipiente_delete'),
)

lume/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('markdown/', include('django_markdown.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    # path('anexos/', include('anexos.urls')),
    url(r'^municipios_app/', include('municipios.urls')),
    path('paises_municipios/', include('paises_municipios.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('analiseagregada/', include('analiseagregada.urls')),
    path('linhaterritorial/', include('linhaterritorial.urls')),
    path('conjunto_organizacoes/', include('conjunto_organizacoes.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
]

urlpatterns += [
    path('agroecossistema/', include('agroecossistema.urls_main')),
    path('agroecossistema/<int:agroecossistema_id>/',
         include('agroecossistema.urls')),
    path('<int:agroecossistema_id>/car/<int:ano_car>/economica/',
         include('economica.urls', namespace='economica')),
    path('<int:agroecossistema_id>/car/<int:ano_car>/simulacao/<str:sim_slug>/economica/',
         include('economica.urls', namespace='ecosim')),
    path('<int:agroecossistema_id>/linhadotempo/', include('linhadotempo.urls')),
    path('<int:agroecossistema_id>/cadernodecampo/',
         include('cadernodecampo.urls')),
    path('<int:agroecossistema_id>/qualitativa/', include('qualitativa.urls')),
    path('<int:agroecossistema_id>/anexos/', include('anexos.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog')
]

urlpatterns += staticfiles_urlpatterns()
if settings.LOCAL:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

anexos/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from django.urls import reverse
from django.utils.translation import gettext as _
from multiupload.fields import MultiFileField

from main.forms import LumeModelForm, LumeForm
from .models import PastaAnexo, Anexo, AnexoRecipiente
from agroecossistema.models import Agroecossistema


class PastaForm(LumeModelForm):

    def __init__(self, *args, **kwargs):
        self.can_delete = kwargs.pop('can_delete', False)

        if self.can_delete:
            agroecossistema_id = kwargs.pop('agroecossistema_id')
            self.delete_confirm_message = _('Deseja realmente apagar esta pasta?')
            self.delete_url = reverse('anexos:pasta_anexo_delete', kwargs={'agroecossistema_id': agroecossistema_id, 'pk': kwargs.get('instance').id})
            self.delete_success_url = reverse('anexos:pasta_anexo_update', kwargs={'agroecossistema_id': agroecossistema_id})
        super(PastaForm, self).__init__(*args, **kwargs)

    class Meta:
        model = PastaAnexo
        fields = ['nome']
        # labels = {
        #     'mae': _('Pasta mãe')
        # }

PastaFormSet = inlineformset_factory(
    Agroecossistema,
    PastaAnexo,
    form=PastaForm,
    can_delete=True,
    extra=1,
    min_num=0
)


class AnexoForm(LumeModelForm):

    def __init__(self, agroecossistema_id = None, *args, **kwargs):
        self.can_delete = kwargs.pop('can_delete', False)
        if self.can_delete:
            self.delete_confirm_message = _('Deseja realmente apagar este arquivo?')
            # self.delete_url = reverse('anexos:anexo_delete_ajax', kwargs={'agroecossistema_id': agroecossistema.id, 'pk': kwargs.get('instance').id})
            # self.delete_success_url = reverse('anexos:anexo_list', kwargs={'agroecossistema_id': agroecossistema.id})

        super(AnexoForm, self).__init__(*args, **kwargs)

        if agroecossistema_id:
            self.fields['pasta'].queryset = PastaAnexo.objects.filter(agroecossistema_id=agroecossistema_id)

    class Meta:
        model = Anexo
        fields = ['arquivo', 'nome', 'descricao', 'pasta']

class AnexoRestForm(LumeModelForm):
    class Meta:
        model = Anexo
        fields = []

class AnexoRecipienteForm(LumeForm):
    arquivos = MultiFileField(min_num=0, required=True)
    descricao = forms.CharField(widget=forms.Textarea, required=False)


class AnexoRecipienteForm(LumeModelForm):
    class Meta:
        model = AnexoRecipiente
        fields = []

anexos/views.py
import os

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from django.views.generic.edit import DeleteView, FormView, FormMixin

from django.utils.translation import gettext as _
from rules.contrib.views import PermissionRequiredMixin

from anexos.mixins import AjaxableResponseMixin
from anexos.utils import organiza_anexos
from cadernodecampo.models import Anotacao
from linhadotempo.models import Evento
from agroecossistema.models import Agroecossistema
from agroecossistema.forms import AgroecossistemaForm
from main.views import LumeDeleteView
from .forms import PastaForm, PastaFormSet, AnexoForm, AnexoRestForm, AnexoRecipienteForm, AnexoRecipienteForm
from .models import PastaAnexo, Anexo, AnexoRecipiente


class PastaListView(ListView):
    model = PastaAnexo


class PastaCreateView(CreateView):
    model = PastaAnexo
    form_class = PastaForm


class PastaDetailView(DetailView):
    model = PastaAnexo


class PastaUpdateView(PermissionRequiredMixin, UpdateView):
    model = Agroecossistema
    form_class = AgroecossistemaForm
    permission_required = 'permissao_padrao'
    titulo = _('Editar Pasta')
    template_name = 'anexos/pasta_form.html'

    def get_permission_object(self):
        agroecossistema = get_object_or_404(Agroecossistema, id=self.kwargs['agroecossistema_id'])
        return agroecossistema

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = self.titulo
        context['modulo'] = 'anexos'
        context['submodulo'] = 'pastas'
        context['agroecossistema'] = Agroecossistema.objects.get(id=self.kwargs['agroecossistema_id'])
        if self.request.POST:
            context['pastas_formset'] = PastaFormSet(self.request.POST, instance=self.get_object())
        else:
            context['pastas_formset'] = PastaFormSet(instance=self.get_object())

        return context

    def get_form_kwargs(self):
        kwargs = super(PastaUpdateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        kwargs.update({'can_delete': self.request.user.has_perm('agroecossistema.apagar', self.get_object())})
        return kwargs

    def form_valid(self, form):
        context = self.get_context_data()
        pastas_formset = context['pastas_formset']

        try:
            with transaction.atomic():
                self.object = form.save()

                if pastas_formset.is_valid():
                    pastas_formset.instance = self.object
                    pastas_formset.save()
                else:
                    tmp = form.full_clean()
                    form._errors[NON_FIELD_ERRORS] = form.error_class([
                        _("Foram encontrados erros no formulário e os dados NÃO foram salvos. Favor fazer as correções indicadas.")
                    ])
                    return self.render_to_response(self.get_context_data(form=form))

        except ValueError:
            tmp = form.full_clean()
            form._errors[NON_FIELD_ERRORS] = form.error_class([
                _("Foram encontrados erros no formulário e os dados NÃO foram salvos. Favor fazer as correções indicadas.")
            ])
            return self.render_to_response(self.get_context_data(form=form))

        return super(PastaUpdateView, self).form_valid(form)

    def get_object(self, queryset=None):
        return Agroecossistema.objects.get(pk=self.kwargs['agroecossistema_id'])

    def get_success_url(self, object_id=None):
        return reverse('anexos:pasta_anexo_update', kwargs={'agroecossistema_id': self.kwargs['agroecossistema_id']})


class PastaDeleteView(PermissionRequiredMixin, LumeDeleteView):
    model = PastaAnexo
    permission_required = 'agroecossistema.alterar'

    def get_permission_object(self):
        agroecossistema = get_object_or_404(Agroecossistema, id=self.kwargs['agroecossistema_id'])
        return agroecossistema

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(PastaDeleteView, self).dispatch(*args, **kwargs)


class AnexoListView(FormMixin, ListView):
    model = Anexo
    template_name = 'anexos/anexo_list.html'
    form_class = AnexoForm

    def get_form_kwargs(self):
        kwargs = super(AnexoListView, self).get_form_kwargs()
        kwargs.update({
            'can_delete': self.request.user.has_perm('permissao_padrao')
        })
        if 'agroecossistema_id' in self.kwargs:
            kwargs['agroecossistema_id'] = self.kwargs['agroecossistema_id']
        if 'data' in kwargs and 'update_pk' in kwargs['data'] and kwargs['data']['update_pk'] != '':
            kwargs['instance'] = Anexo.objects.get(pk=int(kwargs['data']['update_pk']))

        return kwargs

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        anexo = form.save(commit=False)

        anexo.agroecossistema=Agroecossistema.objects.get(pk=self.kwargs['agroecossistema_id'])

        arquivo = form.cleaned_data['arquivo']
        if arquivo.__class__.__name__ == 'InMemoryUploadedFile':
            anexo.mimetype = arquivo.content_type
            if anexo.nome is None or anexo.nome == "":
                anexo.nome = os.path.splitext(arquivo.name)[0]

        anexo.save()

        if 'related_type' in self.kwargs:
            related_type = ContentType.objects.get(app_label=self.kwargs['related_type'], model=self.kwargs['related_model'].lower())
            anexo_recipiente, created = AnexoRecipiente.objects.get_or_create(
                recipiente_object_id=self.kwargs['pk'],
                anexo_id=anexo.id,
                recipiente_content_type_id=related_type.id
            )
            return HttpResponseRedirect(reverse(
                f"{self.kwargs['related_type']}:{self.kwargs['related_model'].lower()}_anexos",
                args=(self.kwargs['agroecossistema_id'],self.kwargs['pk'],)
            ))

        return HttpResponseRedirect(
            reverse('anexos:anexo_list', args=(self.kwargs['agroecossistema_id'],))
        )

    def get_queryset(self):
        relatedType = None
        if 'related_type' in self.kwargs:
            relatedType = self.kwargs['related_type']

        if not relatedType:
            contentType = ContentType.objects.get(app_label='agroecossistema', model='agroecossistema')
            if 'filter' in self.kwargs:
                filter = self.kwargs['filter']
                anexosAll = Anexo.objects.filter(agroecossistema_id=self.kwargs['agroecossistema_id']).order_by('-ultima_alteracao')
                anexos = []
                for anexo in anexosAll:
                    if filter == 'imagens':
                        if anexo.is_image():
                            anexos.append(anexo)
                        continue

                    if filter == 'videos':
                        if anexo.is_video():
                            anexos.append(anexo)
                        continue

                    if not anexo.is_video() and not anexo.is_image():
                        anexos.append(anexo)

            elif 'pastaId' in self.kwargs:
                pastaId = self.kwargs['pastaId']
                anexos = Anexo.objects.filter(agroecossistema_id=self.kwargs['agroecossistema_id'], pasta_id=pastaId).order_by('-ultima_alteracao')

            else:
                anexos = Anexo.objects.filter(agroecossistema_id=self.kwargs['agroecossistema_id']).order_by('-ultima_alteracao')

            return anexos

        # is related content!
        anexosRecipientesList = AnexoRecipiente.objects.filter(recipiente_object_id=self.kwargs['pk']).order_by('-ultima_alteracao').values_list('anexo_id')
        return Anexo.objects.filter(pk__in=anexosRecipientesList)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        relatedType = None
        if 'related_type' in self.kwargs:
            relatedType = self.kwargs['related_type']
        comPastas = True

        if 'agroecossistema_id' in self.kwargs:
            context['agroecossistema'] = Agroecossistema.objects.get(id=self.kwargs['agroecossistema_id'])
        context['modo'] = 'grade' if not ('modo' in self.request.GET) else self.request.GET['modo']
        context['modulo'] = relatedType if relatedType else 'anexos'
        context['isPasta'] = False
        context['titulo'] = _('Anexos')
        context['anexosPlural'] = _('arquivos')
        context['anexosSingular'] = _('arquivo')

        if not relatedType:
            context['submodulo'] = 'todos'
            context['anexosUrlList'] = reverse("anexos:anexo_list", args=(self.kwargs['agroecossistema_id'],))
            context['anexosUrlCreate'] = reverse("anexos:anexo_create", args=(self.kwargs['agroecossistema_id'],))
            if 'filter' in self.kwargs:
                filter = self.kwargs['filter']
                context['submodulo'] = filter
                if filter == 'imagens':
                    context['titulo'] = _("Imagens")
                    context['anexosPlural'] = _("imagens")
                    context['anexosSingular'] = _("imagem")
                elif filter == 'videos':
                    context['titulo'] = _("Vídeos")
                    context['anexosPlural'] = _("vídeos")
                    context['anexosSingular'] = _("vídeo")
                elif filter == 'documentos':

anexos/templates/anexos/inclusiontags/anexosModoGrade.html
{% load i18n %}
{% load l10n %}
{% load rules %}
{% load custom_tags %}
{% load anexos_tags %}

<div id='modoGrade'>
    {% for id, pasta in anexos.anexosOrganizados.items %}
        <div
            id="pasta_{{ id|unlocalize }}"
            class="card bg-pasta mt-4 card-pasta"
            data-qtde="{{ pasta.anexos|length }}"
            ondrop = "drop(event)"
            ondragover = "allowDrop(event)"
            ondragenter = "dragEntered(event)"
            ondragleave = "dragLeft(event)"
        >
            <h5 class="card-title p-2">
                {{ pasta.nome }}
                <span class="small qtdeAnexos">
                    ({% if pasta.anexos|length == 1 %}1 {{ anexosSingular }}{%else%}{{ pasta.anexos|length }} {{ anexosPlural }}{% endif %})
                </span>
            </h5>
            <div class="card-body">
                {% anexosModoGradeCard cardId=pasta.id|unlocalize agroecossistema=agroecossistema anexos=pasta.anexos %}
            </div>
        </div>
    {% endfor %}

    <div
        id="{% if isPasta %}pasta_{{ pasta.id }}{% else %}pasta_solto{% endif %}"
        class="card mt-4 card-pasta"
        data-qtde="{{ anexos.soltos|length }}"
        {% if not isPasta %}
            ondrop = "drop(event)"
            ondragover = "allowDrop(event)"
            ondragenter = "dragEntered(event)"
            ondragleave = "dragLeft(event)"
        {% endif %}
    >
        {% if not isPasta %}
            <h5 class="card-title p-2">
                {{ anexosPlural|title }} {% trans 'sem pasta' %}
                <span class="small qtdeAnexos">
                    ({% if anexos.soltos|length == 1 %}1 {{ anexosSingular }}{%else%}{{ anexos.soltos|length }} {{ anexosPlural }}{% endif %})
                </span>
            </h5>
        {% endif %}
        <div class="card-body">
            {% anexosModoGradeCard cardId="" agroecossistema=agroecossistema anexos=anexos.soltos %}
        </div>
    </div>
</div>

<div class="dropdown-menu dropdown-menu-sm" id="contextMenu">
    <a id="menuBaixar" class="dropdown-item small">
        <i class="fa fa-download mr-2"></i>
        {% trans 'Baixar' %}
    </a>
    <a id="menuEditar" class="dropdown-item small modal-right-open">
        <i class="fa fa-pen mr-2"></i>
        {% trans 'Editar' %}
    </a>
    {% if agroecossistema.pastas.all.count > 0 %}
        <a id="menuMover" class="dropdown-item small">
            <i class="fa fa-folder mr-2"></i>
            {% trans 'Mover para...' %}
        </a>
    {% endif %}
    <a id="menuApagar" class="dropdown-item small">
        <i class="fa fa-times mr-2"></i>
        {% trans 'Apagar' %}
    </a>
    <div class="dropdown-divider"></div>
    <a id="menuCriar" class="dropdown-item small modal-right-open">
        <i class="fa fa-plus mr-2"></i>
        {% trans 'Novo' %}
    </a>
</div>
{% if agroecossistema.pastas.all.count > 0 %}
    <div class="dropdown-menu dropdown-menu-sm" id="contextMenuSub">
        <a class="dropdown-item small context-menu-sub" data-pasta_id="">
            {% trans 'Nenhuma' %}
        </a>
        {% for pasta in agroecossistema.pastas.all %}
            <a class="dropdown-item small context-menu-sub" data-pasta_id="{{ pasta.id }}">
                {{ pasta }}
            </a>
        {% endfor %}
    </div>
{% endif %}

<script>
    const isPasta = {% if isPasta %}true{% else %}false{% endif %};
    const ajaxUrl = `{% url 'anexos:anexo_rest_update' agroecossistema_id=agroecossistema.id %}`
    const anexosPlural = '{{ anexosPlural }}';
    const anexosSingular = '{{ anexosSingular }}';
</script>

anexos/templates/anexos/inclusiontags/anexosModoGradeCard.html
{% load i18n %}
{% load l10n %}
{% load rules %}
{% load anexos_tags %}

<div
    id="{{ cardId }}"
    class="row mt-3 anexos-masonry"
    data-masonry='{"percentPosition": true }'
>
{% for anexo in anexos %}
    <div
        class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-xs-12 anexo"
        ondragstart="drag(event)"
    >
        <div class="card card-anexo mb-4">
            <a
                id="anexo_{{ anexo.id|unlocalize }}"
                data-nome="{{ anexo.nome }}"
                data-descricao="{{ anexo.descricao }}"
                data-arquivo_nome="{{ anexo.arquivo.url|filename }}"
                {% if anexo.pasta %}
                    data-pasta="{{ anexo.pasta.id|unlocalize }}"
                {% endif %}
                href="{{ anexo.arquivo.url }}"
                alt="baixar"
                class="card-anexo-wrapper"
                download="{{ anexo.nome }}"
            >
                {% if anexo.is_image %}
                    <img src="{{ anexo.arquivo.url }}" class="card-img-top anexo-header" alt="">
                {% else %}
                    <div class="card-anexo-no-image anexo-header">
                        <i class="far fa-{{ anexo.get_awesome_icon }}"></i>
                    </div>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ anexo.nome }}</h5>
                    {% if anexo.descricao %}
                        <p class="card-text descricao">
                            {{ anexo.descricao }}
                        </p>
                    {% endif %}
                    {% if anexo.recipientes.all.count > 0 %}
                        <p class="card-text objeto_relacionado">
                            <strong>{{ anexo.recipientes.all.first.recipiente_content_type|title }}:</strong> {{ anexo.recipientes.all.first.recipiente }}
                        </p>
                    {% endif %}
                    <p class="card-text">
                        <small class="text-muted">{{ anexo.criacao }}</small>
                    </p>
                </div>
            </a>
            {% if showMenu %}
                <div class="card-anexo-menu"><i class="fa fa-bars"></i></div>
            {% endif %}
            <div class="card-footer botoes{% if not showFooter %} d-none{% endif %}">
                <a
                    href=""
                    class="caption-apagar"
                    alt="{% trans 'Apagar' %}"
                    data-url="{% url 'anexos:anexo_delete_ajax' agroecossistema_id=agroecossistema.id pk=anexo.id %}"
                    data-filename="{{ anexo.nome }}"
                >
                    {% trans 'Apagar' %}
                </a>
                <a
                    href="{% url 'anexos:anexo_update' agroecossistema_id=agroecossistema.id pk=anexo.id %}"
                    alt="{% trans 'Editar' %}"
                    class="anexo-editar"
                >
                    {% trans 'Editar' %}
                </a>
                <a
                    href="{{ anexo.arquivo.url }}"
                    alt="{% trans 'Baixar' %}"
                    class="anexo-baixar"
                    download="{{ anexo.nome }}"
                >
                    {% trans 'Baixar' %}
                </a>
            </div>
        </div>
    </div>
{% endfor %}
</div>

anexos/templates/anexos/inclusiontags/anexosModoLista.html
{% load i18n %}
{% load l10n %}
{% load rules %}
{% load custom_tags %}
{% load anexos_tags %}

<div id="modoLista" class="mt-3">
    <table
        {% tabela_class tableId='lista_anexos' sticky=True editavel=False searchable=True orderable=True searchIsTitle=True %}
        id="lista_anexos"
        datatable-title="Anexos"
        datatable-filename="Anexos"
    >
        <thead>
            {% if not isPasta and agroecossistema.pastas.all.count > 0 %}
                {% tabela_cabecalho colspan=related_id|yesno:'6,7' tableTitle=titulo targetId='lista_anexos' editavel=False %}
            {% else %}
                {% tabela_cabecalho colspan=related_id|yesno:'5,6' tableTitle=titulo targetId='lista_anexos' editavel=False %}
            {% endif %}
            <tr>
                <th>{% trans "Anexo" %}</th>
                {% if not isPasta and agroecossistema.pastas.all.count > 0 %}
                    <th>{% trans "Pasta" %}</th>
                {% endif %}
                {% if not related_id %}
                    <th>{% trans "Item relacionado" %}</th>
                {% endif %}
                <th>{% trans "Descrição" %}</th>
                <th>{% trans "Criação" %}</th>
                <th>{% trans "Alteração" %}</th>
                <th class="sorting_disabled datatable-export-disabled"></th>
            </tr>
        </thead>
        <tbody>
        {% for id, pasta in anexos.anexosOrganizados.items %}
            {% for anexo in pasta.anexos %}
                {% anexosModoListaRow agroecossistema=agroecossistema anexo=anexo related_id=related_id %}
            {% endfor %}
        {% endfor %}
        {% for anexo in anexos.soltos %}
            {% anexosModoListaRow agroecossistema=agroecossistema anexo=anexo related_id=related_id %}
        {% endfor %}
        </tbody>
    </table>
</div>

<script>
    const isPasta = {% if isPasta %}true{% else %}false{% endif %};
    const ajaxUrl = `{% url 'anexos:anexo_rest_update' agroecossistema_id=agroecossistema.id %}`
    const anexosPlural = '{{ anexosPlural }}';
    const anexosSingular = '{{ anexosSingular }}';
</script>

anexos/templates/anexos/inclusiontags/anexosModoListaRow.html
{% load i18n %}
{% load l10n %}
{% load rules %}
{% load custom_tags %}

<tr id="anexo_{{ anexo.id|unlocalize }}" data-pasta="{{ anexo.pasta.id }}">
    <td>
        <a href="{% url 'anexos:anexo_update' pk=anexo.id agroecossistema_id=agroecossistema.id %}">{{ anexo.nome }}</a>
    </td>
    {% if not isPasta and agroecossistema.pastas.all.count > 0 %}
        <td data-order="{{ anexo.pasta }}">
            <select class="custom-select anexos-table-select">
                <option value=""{% if not anexo.pasta %} selected{% endif %}>
                    Nenhuma
                </option>
                {% for pasta in agroecossistema.pastas.all %}
                    <option value="{{ pasta.id }}"{% if pasta.id == anexo.pasta.id %}selected{% endif %}>
                        {{ pasta }}
                    </option>
                {% endfor %}
            </select>
        </td>
    {% endif %}
    {% if not related_id %}
        <td>
            {% if anexo.recipientes.all.count > 0 %}
                <strong>{{ anexo.recipientes.all.first.recipiente_content_type|title }}:</strong> {{ anexo.recipientes.all.first.recipiente }}
            {% endif %}
        </td>
    {% endif %}
    <td>{{ anexo.descricao }}</td>
    <td data-order="{{ anexo.criacao|date:'U' }}">
        {{ anexo.criacao|date:'d/m/Y' }}
    </td>
    <td data-order="{{ anexo.ultima_alteracao|date:'U' }}">
        {{ anexo.ultima_alteracao|date:'d/m/Y' }}
    </td>
    <td class="sorting_disabled datatable-export-disabled">
        <a
            class="btn btn-danger btn-xs anexos-table-apagar"
            href="#"
            alt="{% trans 'Apagar' %}"
            data-url="{% url 'anexos:anexo_delete_ajax' agroecossistema_id=agroecossistema.id pk=anexo.id %}"
        >
            <i class="fas fa-trash-alt" aria-hidden="true"></i>
        </a>
    </td>
</tr>