agroecossistema/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views, viewsets
from anexos import views as anexo_views

app_name = "agroecossistema"
router = routers.DefaultRouter()
router.register(r"agroecossistema", viewsets.AgroecossistemaViewSet)

urlpatterns = []

urlpatterns += [
    # DRF
    path("api/v1/", include(router.urls)),
]


urlpatterns += (
    # urls for CicloAnualReferencia
    path("car/", views.CicloAnualReferenciaListView.as_view(), name="car_list"),
    # path('car/<int:ano_car>/detail', views.CicloAnualReferenciaDetailView.as_view(),
    path(
        "car/create/", views.CicloAnualReferenciaCreateView.as_view(), name="car_create"
    ),
    path(
        "car/<int:ano_car>/terras/update",
        views.CARTerrasUpdateView.as_view(),
        name="car_update_terras",
    ),
    path(
        "car/<int:ano_car>/composicaonsga",
        views.CARComposicaoUpdateView.as_view(),
        name="car_update_composicao",
    ),
    path(
        "car/<int:ano_car>/delete",
        views.CicloAnualReferenciaDeleteView.as_view(),
        name="car_delete",
    ),
)

urlpatterns += (
    # urls para Simulação
    path(
        "car/<int:ano_car>/simulacao",
        views.SimulacaoListView.as_view(),
        name="sim_list",
    ),
    path(
        "car/<int:ano_car>/create_simulacao",
        views.SimulacaoCreateView.as_view(),
        name="sim_create",
    ),
    path(
        "car/<int:ano_car>/simulacao/<str:sim_slug>/delete",
        views.CicloAnualReferenciaDeleteView.as_view(),
        name="sim_delete",
    ),
    path(
        "car/<int:ano_car>/simulacao/<str:sim_slug>",
        views.CicloAnualReferenciaDetailView.as_view(),
        name="sim_detail",
    ),
    path(
        "car/<int:ano_car>/simulacao/<str:sim_slug>/update",
        views.SimulacaoUpdateView.as_view(),
        name="sim_update",
    ),
    path(
        "car/<int:ano_car>/simulacao/<str:sim_slug>/terras/update",
        views.CARTerrasUpdateView.as_view(),
        name="sim_update_terras",
    ),
    path(
        "car/<int:ano_car>/simulacao/<str:sim_slug>/composicaonsga",
        views.CARComposicaoUpdateView.as_view(),
        name="sim_update_composicao",
    ),
)

urlpatterns += (
    # urls for Pessoa
    path("pessoa/", views.PessoaListView.as_view(), name="pessoa_list"),
    path("pessoa/create/", views.PessoaCreateView.as_view(), name="pessoa_create"),
    # path('pessoa/update/<int:pk>/', views.PessoaUpdateView.as_view(), name='pessoa_update'),
    path(
        "pessoa/delete/<int:pk>/",
        views.PessoaDeleteView.as_view(),
        name="pessoa_delete",
    ),
)

urlpatterns += (
    path(
        "comparar",
        views.AnaliseCompareFormView.as_view(),
        name="analise_compara_escolha",
    ),
    path(
        "comparar_sim/<int:ano_car>/simulacao/<str:sim_slug>",
        views.AnaliseCompareSimView.as_view(),
        name="analise_compara_escolha_simulacao",
    ),
    path(
        "comparar/<int:analise_id_1>/<int:analise_id_2>",
        views.AnaliseCompareView.as_view(),
        name="analise_compara",
    ),
)

economica/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = 'economica'

urlpatterns = []

urlpatterns += (
    # urls for Analise
    path('update', views.AnaliseUpdateView.as_view(), name='analise_update'),
    path('relatorios', views.AnaliseDetailView.as_view(), name='analise_detail'),
    # path('painel-graficos',
    #     views.AnalisesPainelGraficosView.as_view(),
    #     name='painel-graficos'),
    path('painel-graficos',
         views.AnalisesPainelGraficosCarouselView.as_view(),
         name='painel-graficos'),
    path('delete', views.AnaliseDeleteView.as_view(), name='analise_delete'),
    path('estoqueinsumos', views.EstoqueInsumosUpdateView.as_view(), name='estoqueinsumos_update'),
    path('pagamentoterceiros', views.PagamentoTerceirosUpdateView.as_view(),
         name='pagamentoterceiros_update'),
    path('patrimonio/F', views.PatrimonioUpdateView.as_view(tipo='F'), name='patrimonio_F_update'),
    path('patrimonio/E', views.PatrimonioUpdateView.as_view(tipo='E'), name='patrimonio_E_update'),
    path('patrimonio/V', views.PatrimonioUpdateView.as_view(tipo='V'), name='patrimonio_V_update'),
    path('rendanaoagricola/T', views.RendaNaoAgricolaUpdateView.as_view(tipo="T"),
         name='rendanaoagricola_T_update'),
    path('rendanaoagricola/P', views.RendaNaoAgricolaUpdateView.as_view(tipo="P"),
         name='rendanaoagricola_P_update'),
    path('tempotrabalho', views.TempoTrabalhoUpdateView.as_view(), name='tempotrabalho_update'),

)

# Subsistema
urlpatterns += (
    path('subsistema', views.SubsistemaListView.as_view(),
        name='subsistema_list'),
    path('subsistema/vazio', views.SubsistemaVazioView.as_view(),
        name='subsistema_vazio'),
    path('subsistema/<int:pk>/insumo/P', views.SubsistemaInsumoUpdateView.as_view(tipo='P'),
        name='subsistemainsumo_P_update'),
    path('subsistema/<int:pk>/insumo/C', views.SubsistemaInsumoUpdateView.as_view(tipo='C'),
        name='subsistemainsumo_C_update'),
    path('subsistema/<int:pk>/pagamentoterceiros',
        views.SubsistemaPagamentoTerceirosUpdateView.as_view(),
        name='subsistemapagamentoterceiros_update'),
    path('subsistema/<int:pk>/aquisicaoreciprocidade/I',
        views.SubsistemaAquisicaoReciprocidadeUpdateView.as_view(tipo='I'),
        name='subsistemaaquisicaoreciprocidade_I_update'),
    path('subsistema/<int:pk>/aquisicaoreciprocidade/S',
        views.SubsistemaAquisicaoReciprocidadeUpdateView.as_view(tipo='S'),
        name='subsistemaaquisicaoreciprocidade_S_update'),
    path('subsistema/<int:pk>/tempo_trabalho', views.SubsistemaTempoTrabalhoUpdateView.as_view(),
        name='subsistematempotrabalho_update'),
    path('subsistema/<int:pk>/producao', views.SubsistemaProducaoUpdateView.as_view(),
        name='subsistemaproducao_update'),
)

lume/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('markdown/', include('django_markdown.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    # path('anexos/', include('anexos.urls')),
    url(r'^municipios_app/', include('municipios.urls')),
    path('paises_municipios/', include('paises_municipios.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('analiseagregada/', include('analiseagregada.urls')),
    path('linhaterritorial/', include('linhaterritorial.urls')),
    path('conjunto_organizacoes/', include('conjunto_organizacoes.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
]

urlpatterns += [
    path('agroecossistema/', include('agroecossistema.urls_main')),
    path('agroecossistema/<int:agroecossistema_id>/',
         include('agroecossistema.urls')),
    path('<int:agroecossistema_id>/car/<int:ano_car>/economica/',
         include('economica.urls', namespace='economica')),
    path('<int:agroecossistema_id>/car/<int:ano_car>/simulacao/<str:sim_slug>/economica/',
         include('economica.urls', namespace='ecosim')),
    path('<int:agroecossistema_id>/linhadotempo/', include('linhadotempo.urls')),
    path('<int:agroecossistema_id>/cadernodecampo/',
         include('cadernodecampo.urls')),
    path('<int:agroecossistema_id>/qualitativa/', include('qualitativa.urls')),
    path('<int:agroecossistema_id>/anexos/', include('anexos.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog')
]

urlpatterns += staticfiles_urlpatterns()
if settings.LOCAL:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

agroecossistema/templates/agroecossistema/inclusiontags/painel_analises_qualitativas.html
{% load i18n %}
{% load custom_tags %}
{% load agroecossistema_tags %}

{% for atributo_id, atributo in atributos.items %}
<div class="row mt-5 download-chart-{{ atributo_id }}">
  <div class="col-md-12">
    <div class="d-flex justify-content-between align-items-baseline">
      <h4 class="tableTitle">{% trans "Gráfico" %}</h4>
      <a id="link-{{ atributo_id }}" class="btn btn-outline-secondary">
        <i class="fa fa-download"></i>
      </a>
    </div>
  </div>
</div>
<div class="row mt-5">
  <div class="col-md-12 d-flex justify-content-center"
       id="aranha-wrapper-{{ atributo_id }}">
    <div id="aranhaEmpty-{{ atributo_id }}" class="aranhaEmpty">
      <div class="alert alert-info">
        {% trans "Não há dados suficientes para mostrar o gráfico. Ele só será exibido quando todos os parâmetros deste atributo forem preenchidos. Caso queira eliminar parâmetros, clique no botão 'configurar análises' acima." %}
      </div>
    </div>
    <canvas id="aranha-{{ atributo_id }}" class="chartCanvas legendsRight"></canvas>
  </div>
</div>
{% endfor %}

agroecossistema/templates/agroecossistema/inclusiontags/painel_cabecalho.html
{% load i18n %}
{% load custom_tags %}
{% load agroecossistema_tags %}

<h3 class="mb-3">{{ agroecossistema }}</h3>
{% if not sim_slug %}
  <p>
    {% if agroecossistema.territorio %}
      {% blocktrans %}O agroecossistema{% endblocktrans %} <strong>{{ agroecossistema }}</strong>
      {% blocktrans %}está localizado na comunidade{% endblocktrans %}
      <a href="{% url 'comunidade_detail' pk=agroecossistema.comunidade.id %}">{{ agroecossistema.comunidade.nome }}</a>, {% blocktrans %}no território{% endblocktrans %} <a href="{% url 'territorio_detail' pk=agroecossistema.territorio.id %}">{{ agroecossistema.territorio }}</a>,
    {% else %}
      {% blocktrans %}O agroecossistema{% endblocktrans %} <strong>{{ agroecossistema }}</strong>
      {% blocktrans %}está localizado na comunidade{% endblocktrans %}
      <a href="{% url 'comunidade_detail' pk=agroecossistema.comunidade.id %}">{{ agroecossistema.comunidade.nome }}</a>,
    {% endif %}
    {% blocktrans %}em{% endblocktrans %} {{ agroecossistema.comunidade.municipio }} - {{ agroecossistema.comunidade.municipio.uf.sigla }}.
    {% if car.terras.count %}
      {% blocktrans %}São {% endblocktrans %}{{ car.get_area_total|floatformat:1 }} {% blocktrans %}hectares de terra, das quais{% endblocktrans %}
      {% get_terras_list car=car tipo=tipo_sigla as terra_list %}
      {% for terra in terra_list %}
        {% if forloop.last %}e{% endif %}
        {{ terra.area|floatformat:0 }}<i>ha</i> como
        {% if forloop.last %}
          {{ terra.tipo }}.
        {% else %}
          {{ terra.tipo }},
        {% endif %}
      {% endfor %}
    {% endif %}
  </p>
  <p>
    {% blocktrans %}A organização responsável pelo cadastro é a{% endblocktrans %} <strong>{{ object.organizacao }}</strong>. {% blocktrans %}A última alteração no agroecossistema se deu em{% endblocktrans %} {{ agroecossistema.ultima_alteracao }}.
  </p>
{% else %}
  <strong>{{ car }}</strong>
  <br />
  <i>{{ car.sim_descricao }}</i>
{% endif %}

<div class="alert alert-info d-flex" role="alert">
  <div class="row">
    <div class="col-1 text-center">
      <i class="icon-panel-info" aria-hidden="true"></i>
    </div>
    <div class="col-11">
      {% blocktrans %}
      As informações abaixo apresentam dados das análises econômicas realizadas no período de {{ car }}.
      Selecione outro ciclo de referência para ver as análises de outro período.
      {% endblocktrans %}
    </div>
    <div class="col-1">
      &nbsp;
    </div>
    <div class="col-11 mt-2">
      {% include "main/partials/ciclo_selector.html" %}
    </div>
  </div>
</div>

agroecossistema/templates/agroecossistema/inclusiontags/painel_caracterizacao.html
{% load i18n %}
{% load custom_tags %}
{% load agroecossistema_tags %}

{##########################################}
{############# COMPOSICAO NSGA ############}
{##########################################}
{% if car.composicoes_nsga.count %}
<table {% tabela_class editavel=False tableId='composicao_nsga' sticky=False %}
  id="composicao_nsga">
  <thead>
    {% tabela_cabecalho colspan=5 tableTitle="NSGA"|concat:': '|concat:object.nsga targetId='composicao_nsga' editavel=False %}
    <tr>
      <th>{% trans "Nome" %}</th>
      <th>{% trans "Sexo" %}</th>
      <th>{% trans "Idade" %}</th>
      <th>{% ajudaIndicador slug="UTF" %} {% trans "Agr." %}</th>
      <th>{% ajudaIndicador slug="UTF" %} {% trans "Plur." %}</th>
    </tr>
  </thead>
  <tbody>
    {% for horas_p in analise_economica.totais_horastrabalhoporpessoa.all %}
    <tr>
      <td>
        {{ horas_p.pessoa_nome }}
        {% if horas_p.responsavel %}
        <span class="asteriskField"
              title="Responsável pelo {% ajudaIndicador slug='NSGA' %}">*</span>
        {% else %}
        ({{ horas_p.get_grau_de_parentesco_display }})
        {% endif %}
      </td>
      <td>{{ horas_p.get_pessoa_sexo_display }}</td>
      <td>{{ horas_p.get_idade }}</td>
      <td>{{ horas_p.utf_agroecossistema|floatformat:2 }}</td>
      <td>{{ horas_p.utf_pluriatividade|floatformat:2 }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<div class="alert alert-secondary mb-0">
  {% trans "Ainda não há pessoas cadastradas no" %} {% ajudaIndicador slug="NSGA" %}.
</div>
{% endif %}

<br />

{#################################}
{############# TERRAS ############}
{#################################}
{% if car.terras.count %}
{% trans "Terras" as Terras %}
<table {% tabela_class editavel=False tableId='terras' sticky=False %}
  id="terras">
  <thead>
    {% tabela_cabecalho colspan=3 tableTitle=Terras targetId='terras' editavel=False %}
    <tr>
      <th>{% trans "Tipo" %}</th>
      <th>{% trans "Unid." %}</th>
      <th>{% trans "Área (ha)" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for tipo_sigla, tipo_nome in car.terras.first.TIPOS_TERRA %}
    {% get_terras car=car tipo=tipo_sigla as terra %}
    {% if terra.qtde %}
    <tr>
      <td>{{ tipo_nome }}</td>
      <td>{{ terra.qtde }}</td>
      <td>{{ terra.area }}</td>
    </tr>
    {% endif %}
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <th>{% trans "TOTAL" %}</th>
      <th>{{ car.terras.count }}</th>
      <th>{{ car.get_area_total|floatformat:2 }}</th>
    </tr>
  </tfoot>
</table>
{% else %}
<div class="alert alert-secondary mb-0">{% trans "Ainda não há terras registradas." %}</div>
{% endif %}

<br>

{######################################}
{############# SUBSISTEMAS ############}
{######################################}
{% if subsistemas_object_list|length > 0 %}
  <div class="row">
    <div class="col-sm-12">
      <table
        {% tabela_class tableId='lista_subsistemas' sticky=True editavel=False searchable=True orderable=True searchIsTitle=True %}
        id="lista_subsistemas"
        datatable-title="Lista de subsistemas"
        datatable-filename="lista_subsistemas"
        >
        <thead>
          {% tabela_cabecalho colspan=4 tableTitle='Subsistemas' targetId='lista_subsistemas' editavel=False %}
          <tr>
            <th>{% trans "Subsistema" %}</th>
            <th>{% trans "Área (ha)" %}</th>
            <th>{% trans "Observações" %}</th>
            <th>{% trans "Criado em" %}</th>
          </tr>
        </thead>
        <tbody>
          {% for object in subsistemas_object_list %}
          <tr>
            <td>{{ object }}</td>
            <td>{% if object.area is not None %}{{ object.area }}{% endif %}</td>
            <td>{% if object.observacoes is not None %}{{ object.observacoes }}{% endif %}</td>
            <td>{{ object.criacao }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% else %}
  <div class="row mt-3">
    <div class="col-md-12 mt-2">
      <div class="alert alert-info">
        <h5>
          {% trans 'Ainda nao há subsistemas cadastrados.' %}
          {% if pode_cadastrar_subsistema %}
          {% trans "Seja a/o primeira/o a criar um" %} <a href="{{ car.get_subsistema_create_url }}">
            {% trans "clique aqui" %}</a>.
          {% endif %}
        </h5>
      </div>
    </div>
  </div>
{% endif %}

<script>
  action_buttons = $('#composicao_nsga .tableButtons').html();
  url_button = "{% url 'agroecossistema:car_update_composicao' agroecossistema.id ano_car %}"
  btn_title_attr = "{% trans 'abrirá em outra aba' %}";
  edit_button = '<div style="background-color:#fff;" class="ml-2">\
  <a href="'+url_button+'" class="btn btn-outline-primary" target="blank" title="'+btn_title_attr+'">\
            <i class="fa fa-pen mr-1" aria-hidden="true"></i>\
            Editar</a><div>';
  // $('#composicao_nsga .tableButtons').html(action_buttons+edit_button);
  $('#composicao_nsga .tableButtons').html(edit_button);

  action_buttons = $('#terras .tableButtons').html();
  url_button = "{% url 'agroecossistema:car_update_terras' agroecossistema.id ano_car %}"
  edit_button = '<div style="background-color:#fff;" class="ml-2">\
  <a href="'+url_button+'" class="btn btn-outline-primary" target="blank" title="'+btn_title_attr+'">\
            <i class="fa fa-pen mr-1" aria-hidden="true"></i>\
            Editar</a><div>';
  // $('#terras .tableButtons').html(action_buttons+edit_button);
  $('#terras .tableButtons').html(edit_button);

  action_buttons = $('#lista_subsistemas .tableButtons').html();
  url_button = "{% url 'economica:subsistema_list' agroecossistema.id ano_car %}"
  edit_button = '<div style="background-color:#fff;" class="ml-2">\
  <a href="'+url_button+'" class="btn btn-outline-primary" target="blank" title="'+btn_title_attr+'">\
            <i class="fa fa-pen mr-1" aria-hidden="true"></i>\
            Editar</a><div>';
  // $('#lista_subsistemas .tableButtons').html(action_buttons+edit_button);
  $('#lista_subsistemas .tableButtons').html(edit_button);
</script>