linhadotempo/urls.py
# debug NoReverseMatch:
# https://overiq.com/django-1-11/creating-urls-and-custom-response/

from django.urls import path
from . import views
from anexos import views as anexosViews

app_name = 'linhadotempo'
urlpatterns = (
    # urls for Evento
    path('', views.EventoListView.as_view(), name='evento_list'),

    # painel agroecossistema
    path('painel/linhadotempo/',
         views.PainelAgroecossistemaEventoListView.as_view(),
         name='painel_evento_list'),
    path('painel/evento/create/',
         views.PainelAgroecossistemaEventoCreateView.as_view(),
         name="painel_evento_create"),

    path('eventos/detail/<int:pk>/', views.EventoDetailView.as_view(),
         name='evento_detail'),
    path('eventos/delete/<int:pk>/', views.EventoDeleteView.as_view(),
         name='evento_delete'),
    path('eventos/anexos/<int:pk>/', anexosViews.AnexoListView.as_view(), {'related_type': 'linhadotempo', 'related_model': 'Evento'}, name='evento_anexos'),
    path('eventos/rest/update', views.EventoRestUpdateView.as_view(), name="evento_rest_update"),
    path('eventos/rest/delete', views.EventoRestDeleteView.as_view(), name="evento_rest_delete"),
)

urlpatterns += (
    # urls for EventoGrupo
    path('eventogrupo/', views.EventoGrupoListView.as_view(), name='eventogrupo_list'),
    path('eventogrupo/create/', views.EventoGrupoCreateView.as_view(), name='eventogrupo_create'),
    path('eventogrupo/detail/<int:pk>/', views.EventoGrupoDetailView.as_view(), name='eventogrupo_detail'),
    path('eventogrupo/update/<int:pk>/', views.EventoGrupoUpdateView.as_view(), name='eventogrupo_update'),
)

linhaterritorial/urls.py
from django.urls import path
from . import views
from anexos import views as anexosViews

app_name = 'linhaterritorial'
urlpatterns = (
    path('anexos/comunidade/<int:pk>/', anexosViews.AnexoListView.as_view(), {'related_type': 'linhaterritorial', 'related_model': 'EventoTerritorial', 'related_list_url': 'comunidade_linhaterritorial'}, name='comunidade_anexos'),
    path('anexos/territorio/<int:pk>/', anexosViews.AnexoListView.as_view(), {'related_type': 'linhaterritorial', 'related_model': 'EventoTerritorial', 'related_list_url': 'territorio_linhaterritorial'}, name='territorio_anexos'),
    path('evento_territorial/rest/update', views.EventoTerritorialRestUpdateView.as_view(), name="evento_rest_update"),
    path('evento_territorial/rest/delete', views.EventoTerritorialRestDeleteView.as_view(), name="evento_rest_delete"),
)

lume/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('markdown/', include('django_markdown.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    # path('anexos/', include('anexos.urls')),
    url(r'^municipios_app/', include('municipios.urls')),
    path('paises_municipios/', include('paises_municipios.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('analiseagregada/', include('analiseagregada.urls')),
    path('linhaterritorial/', include('linhaterritorial.urls')),
    path('conjunto_organizacoes/', include('conjunto_organizacoes.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
]

urlpatterns += [
    path('agroecossistema/', include('agroecossistema.urls_main')),
    path('agroecossistema/<int:agroecossistema_id>/',
         include('agroecossistema.urls')),
    path('<int:agroecossistema_id>/car/<int:ano_car>/economica/',
         include('economica.urls', namespace='economica')),
    path('<int:agroecossistema_id>/car/<int:ano_car>/simulacao/<str:sim_slug>/economica/',
         include('economica.urls', namespace='ecosim')),
    path('<int:agroecossistema_id>/linhadotempo/', include('linhadotempo.urls')),
    path('<int:agroecossistema_id>/cadernodecampo/',
         include('cadernodecampo.urls')),
    path('<int:agroecossistema_id>/qualitativa/', include('qualitativa.urls')),
    path('<int:agroecossistema_id>/anexos/', include('anexos.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog')
]

urlpatterns += staticfiles_urlpatterns()
if settings.LOCAL:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

linhadotempo/models.py
import json
from datetime import datetime

from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.db.models import TextField
from django.urls import reverse
from django_markdown.models import MarkdownField

from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _lazy

from main.models import Organizacao
from anexos.models import AnexoRecipiente
from lume.models import LumeModel
from agroecossistema.models import Agroecossistema
from main.messages_from_db import linhadotempo_helpers


class TipoDimensao(LumeModel):
    nome = models.CharField(max_length=80, verbose_name=_lazy("nome"))

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ("nome",)


class Dimensao(LumeModel):
    nome = models.CharField(max_length=80, verbose_name=_lazy("nome"))
    tipo_dimensao = models.ForeignKey(
        TipoDimensao,
        models.PROTECT,
        verbose_name=_lazy("tipo da dimensão"),
        related_name="dimensoes",
    )
    ordem = models.SmallIntegerField(null=True, verbose_name=_lazy("ordem"))
    descricao = MarkdownField(null=True, blank=True, verbose_name=_lazy("descrição"))

    HELPERS = linhadotempo_helpers

    def __str__(self):
        return self.tipo_dimensao.nome + " / " + self.nome

    class Meta:
        ordering = (
            "tipo_dimensao__nome",
            "ordem",
        )


class EventoGatilho(LumeModel):
    organizacao = models.ForeignKey(
        Organizacao, models.PROTECT, verbose_name=_lazy("organização")
    )
    dimensao = models.ForeignKey(
        Dimensao, models.PROTECT, verbose_name=_lazy("dimensão")
    )
    titulo = models.CharField(max_length=80, verbose_name=_lazy("título"))
    detalhes = TextField(verbose_name=_lazy("detalhes"))

    class Meta:
        ordering = ("titulo",)

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse("eventogatilho_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("eventogatilho_update", args=(self.pk,))

    def save(self):
        super().save()

        # Atualiza os eventos relacionados ao Evento-gatilho alterado
        self.eventos_relacionados.all().update(
            titulo=self.titulo, dimensao=self.dimensao
        )


class Evento(LumeModel):
    data_inicio = models.PositiveSmallIntegerField(verbose_name=_lazy("data inicial"))
    data_fim = models.PositiveSmallIntegerField(
        null=True, blank=True, verbose_name=_lazy("data final")
    )
    evento_gatilho = models.ForeignKey(
        EventoGatilho,
        models.PROTECT,
        null=True,
        blank=True,
        verbose_name=_lazy("evento-gatilho"),
        related_name="eventos_relacionados",
    )
    titulo = models.CharField(max_length=80, verbose_name=_lazy("título"))
    detalhes = TextField(null=True, blank=True, verbose_name=_lazy("detalhes"))
    dimensao = models.ForeignKey(
        Dimensao, models.PROTECT, verbose_name=_lazy("dimensão")
    )
    agroecossistema = models.ForeignKey(
        Agroecossistema,
        models.CASCADE,
        related_name="eventos",
        verbose_name=_lazy("agroecossistema"),
    )
    criado_por = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        models.DO_NOTHING,
        null=True,
        blank=True,
        verbose_name=_lazy("criado por"),
    )
    anexos = GenericRelation(
        AnexoRecipiente,
        verbose_name=_lazy("anexos"),
        content_type_field="recipiente_content_type",
        object_id_field="recipiente_object_id",
    )
    criacao = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name=_lazy("criação")
    )
    ultima_alteracao = models.DateTimeField(
        auto_now=True, editable=False, verbose_name=_lazy("última alteração")
    )

    class Meta:
        ordering = ("-pk",)

    def __str__(self):
        return self.titulo

    def __unicode__(self):
        return "%s" % self.pk

    def get_absolute_url(self):
        return (
            reverse(
                "linhadotempo:evento_list",
                kwargs={"agroecossistema_id": self.agroecossistema_id},
            )
            + "?evento_id="
            + str(self.pk)
        )

    def as_visjs_json(self):
        visjs_json = {
            "id": self.id,
            "start": datetime(self.data_inicio, 1, 3),
            "content": self.titulo,
            "group": self.dimensao_id,
            "titulo": self.titulo,
            "detalhes": self.detalhes,
            "anexos_url": self.get_anexos_url(),
            "title": self.titulo,
            "evento_gatilho": (
                None if self.evento_gatilho == None else self.evento_gatilho.id
            ),
            "className": "" if self.evento_gatilho == None else "evento_gatilho",
        }

        if self.criado_por is not None:
            visjs_json["autor"] = self.criado_por.get_username()

        if self.data_fim is not None:
            visjs_json["end"] = datetime(self.data_fim, 12, 30)
        else:
            visjs_json["end"] = datetime(self.data_inicio, 12, 30)

        if (
            self.data_fim != ""
            and self.data_fim is not None
            and self.data_inicio != self.data_fim
        ):
            visjs_json["ano_formatted"] = (
                str(self.data_inicio) + "-" + str(self.data_fim)
            )
        else:
            visjs_json["ano_formatted"] = str(self.data_inicio)

        visjs_json["anexos"] = list(self.get_anexos_list())

        return json.dumps(visjs_json, cls=DjangoJSONEncoder)

    def get_anexos_url(self):
        current_type_id = ContentType.objects.get_by_natural_key(
            self._meta.app_label, self._meta.model_name
        )
        return reverse(
            "anexos:anexo_list", kwargs={"agroecossistema_id": self.agroecossistema.id}
        )

    def get_anexos_list(self):
        a_list = []
        anexo_rs = self.anexos.all()
        for anexo_r in anexo_rs:
            anexo = anexo_r.anexo
            a_list.append(anexo.as_dict())
        return a_list

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)
        if (
            self.data_fim is not None
            and self.data_inicio is not None
            and self.data_fim < self.data_inicio
        ):
            raise ValidationError(_("Ano final deve ser maior que ano inicial."))

    def save(self, *args, **kwargs):
        # update ultima_alteracao of agroecossistema:
        self.agroecossistema.save()
        super(Evento, self).save(*args, **kwargs)


class EventoGrupo(LumeModel):
    nome = models.CharField(max_length=255, verbose_name=_lazy("nome"))
    descricao = models.TextField(null=True, blank=True, verbose_name=_lazy("descrição"))
    agroecossistema = models.ForeignKey(
        Agroecossistema, models.CASCADE, verbose_name=_lazy("agroecossistema")
    )
    criacao = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name=_lazy("criação")
    )
    ultima_alteracao = models.DateTimeField(
        auto_now=True, editable=False, verbose_name=_lazy("última alteração")
    )

    # Relationship Fields
    eventos = models.ManyToManyField(
        "linhadotempo.Evento",
        verbose_name=_lazy("eventos"),
        related_name="grupos",
    )

    class Meta:
        ordering = ("-criacao",)

    def __unicode__(self):
        return "%s" % self.pk

    def get_absolute_url(self):
        return reverse(
            "linhadotempo:eventogrupo_detail",
            args=(
                self.agroecossistema_id,
                self.pk,
            ),
        )

    def get_update_url(self):
        return reverse(
            "linhadotempo:eventogrupo_update",
            args=(
                self.agroecossistema_id,
                self.pk,
            ),
        )

linhadotempo/templates/linhadotempo/evento_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    {{ form.media }}
    <h4>{{ titulo }}</h4>
    <br/>
    {% crispy form %}

{% endblock %}

{% block includes %}
    <script type="text/javascript">
        var CHECKBOX_GATILHO = '#id_is_gatilho';

        function initFormEvento () {
            is_gatilho = $(CHECKBOX_GATILHO).is(':checked');

            $('#id_evento_gatilho').attr('disabled', !is_gatilho);
            $('#id_evento_gatilho').next('.invalid-feedback').eq(0).toggle(is_gatilho);
            $('#id_titulo').attr('disabled', is_gatilho);
            $('#id_titulo').next('.invalid-feedback').eq(0).toggle(!is_gatilho);
            $('#id_dimensao').attr('disabled', is_gatilho);
            $('#id_dimensao').next('.invalid-feedback').eq(0).toggle(!is_gatilho);
        }

        $(document).ready(function () {
            $(CHECKBOX_GATILHO)
              .ready(initFormEvento)
              .on('click', initFormEvento);
        });
    </script>
{% endblock %}

linhadotempo/templates/linhadotempo/evento_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load vstatic %}
{% load crispy_forms_tags %}
{% load rules %}
{% if isTerritorial %}
    {% load linhaterritorial_tags %}
{% endif %}
{% block titulo_navbar %}
    {% if isTerritorial %}
        {% trans modulo|title %}
    {% else %}
        {% trans "Agroecossistema" %}
    {% endif %}
    : {{ titulo }}
{% endblock titulo_navbar %}
{% block includes %}
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
    <script type="text/javascript"
            src="https://unpkg.com/vis-timeline/standalone/umd/vis-timeline-graph2d.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/latest/plugins/CSSPlugin.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenLite.min.js"></script>
    <script src="https://www.greensock.com/js/src/utils/Draggable.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/i18n/pt-BR.js"></script>
    <script src="{% vstatic 'main/js/eventos_form_helpers.js' %}"
            type="text/javascript"></script>
    <script src="{% vstatic 'linhadotempo/js/linhadotempo.js' %}"
            type="text/javascript"></script>
    <script src="{% vstatic 'main/js/html2canvas.min.js' %}"></script>
    <script type="text/javascript">
        const isTerritorial = {{ isTerritorial|yesno:'true,false' }};
        const initialWindowSize = 6;
        const grupos = {{ grupos|safe }};
        let dataInicio;
        let dataFim;
        {% if isTerritorial %}
            const eventos = {{ object_list|as_visjs_json|safe }};
            const restUpdateUrl = '{% url "linhaterritorial:evento_rest_update" %}';
            const restDeleteUrl = '{% url "linhaterritorial:evento_rest_delete" %}';
            const comunidadeOuTerritorioId = '{{ comunidadeOuTerritorio.id }}';
            const agroecossistemaId = null;
            const contentTypeId = '{{ content_type.id }}';
            const periodos = {{ periodos|safe }};
            let ajax_tipo_dimensao_id = "";
            const ajax_tipos_dimensao_url = "{% url modulo|add:'_linhaterritorial_api_tipos_dimensao' pk=comunidadeOuTerritorio.id %}";
            const ajax_dimensoes_url = "{% url modulo|add:'_linhaterritorial_api_dimensoes' pk=comunidadeOuTerritorio.id %}";
            dataInicio = moment(`${1900 + periodos[0].coluna}-01-03T00:00:00`).valueOf();
            dataFim = moment(`${1900 + periodos[periodos.length - 1].coluna}-12-30T00:00:00`).valueOf();
        {% else %}
            const eventos = [{% for object in object_list %}{{ object.as_visjs_json|safe }}{% if not forloop.last %}, {% endif %}{% endfor %}];
            const restUpdateUrl = '{% url "linhadotempo:evento_rest_update" agroecossistema_id=agroecossistema.id %}';
            const restDeleteUrl = '{% url "linhadotempo:evento_rest_delete" agroecossistema_id=agroecossistema.id %}';
            const agroecossistemaId = "{{ agroecossistema.id }}";
            const comunidadeOuTerritorioId = null;
        {% endif %}

        $(document).ready(function () {
            initLinhaDoTempo();
        });
    </script>
    {{ form.media }}
{% endblock includes %}
{% block content %}
    {% if isTerritorial %}
        {% has_perm 'permissao_padrao' user as pode_alterar_linhadotempo %}
    {% else %}
        {% has_perm 'agroecossistema.alterar' user agroecossistema as pode_alterar_linhadotempo %}
    {% endif %}
    <div class="toast d-none"
         role="alert"
         aria-live="assertive"
         aria-atomic="true">
        <div class="toast-header">
            <strong class="mr-auto" id="toastTitle">Salvo</strong>
            <button type="button"
                    class="ml-2 mb-1 close"
                    data-dismiss="toast"
                    aria-label="Fechar">
                <span aria-hidden="true">×</span>
            </button>
        </div>
        <div class="toast-body">O evento "" foi atualizado!</div>
    </div>
    <div class="row linhadotempoHeaders">
        <div id="buscaEventosWrapper" class="col-sm-6 col-md-4 col-lg-3">
            <label>
                <i class="fa fa-search"></i>
            </label>
            <select id="buscaEventos" name="buscaEventos">
                <option>vazio</option>
            </select>
        </div>
        <div class="col-sm-6 col-md-8 col-lg-9 text-right">
            <a class="btn btn-secondary mt-2 mb-2"
               id="download_linhadotempo"
               href=""
               download="{{ titulo }}_linhadotempo.png">{% trans "Exportar" %}</a>
        </div>
    </div>
    <div class="row mb-2 linhadotempoHeaders">
        <div class="col-sm-8 col-md-10 col-lg-10">
            <div id="linhadotempoSlider">
                <div id="linhadotempoSliderHolder" class="dragMove"></div>
                <div id="linhadotempoSliderHolderLeft" class="dragResize"></div>
                <div id="linhadotempoSliderHolderRight" class="dragResize"></div>
            </div>
        </div>
        <div class="col-sm-4 col-md-2 col-lg-2 text-right">
            <span class="btn btn-secondary btn-xsm" id="zoomIn" title="ampliar"><i class="fas fa-plus"></i></span>
            <span class="btn btn-secondary btn-xsm disabled"
                  id="zoomOut"
                  title="reduzir"><i class="fas fa-minus"></i></span>
            <span class="btn btn-secondary btn-xsm disabled"
                  id="seeAll"
                  title="ver tudo"><i class="fas fa-compress-arrows-alt"></i></span>
        </div>
    </div>
    <div class="row">
        <div class="linhadotempo_pane1 col-md-12">
            <div id="linhadotempo" class="linhadotempo_holder"></div>
            {% if pode_alterar_linhadotempo %}
                <div id="modoEdicaoWrapper" class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="modoEdicao">
                    <label class="custom-control-label" for="modoEdicao">Edição</label>
                </div>
            {% endif %}
        </div>
        <div class="dropdown-menu dropdown-menu-sm" id="contextMenu">
            <a id="menuVer" class="dropdown-item small"><i class="fa fa-eye mr-2 modal-right-open"></i>Ver evento</a>
            <a id="menuEditar" class="dropdown-item small"><i class="fa fa-pen mr-2 modal-right-open"></i>Editar</a>
            <a id="menuApagar" class="dropdown-item small"><i class="fa fa-times mr-2"></i>Apagar</a>
            <a id="menuCriar" class="dropdown-item small"><i class="fa fa-plus mr-2 modal-right-open"></i>Novo evento</a>
            <div class="dropdown-divider"></div>
            <a id="menuFit" class="dropdown-item small"><i class="fa fa-arrows-alt mr-2"></i>Ver tudo</a>
            {% if pode_alterar_linhadotempo %}
                <a id="menuAtivaEdicao" class="dropdown-item small"><i class="fa fa-tools mr-2"></i>Modo de edição</a>
            {% endif %}
            <a id="menuDesativaEdicao" class="dropdown-item small"><i class="fa fa-search mr-2"></i>Modo de visualização</a>
        </div>
    </div>
{% endblock content %}
{% block modal_right_title %}
    {% if not isTerritorial %}
        <div class="eventoFormDiv">
            <h5 class="modal-right-title"></h5>
        </div>
        <div class="eventoDetailDiv">
            <h5 class="modal-right-title"></h5>
            <div id="eventoModalBadgeGatilho" class="badge badge-warning">{% trans "evento-gatilho" %}</div>
        </div>
    {% endif %}
{% endblock modal_right_title %}
{% block modal_right_body %}
    <div class="eventoFormDiv">
        <div>
            {% csrf_token %}
            {% for f in form.invisible_fields %}{{ f.id_for_label }}{% endfor %}
            {{ form|crispy }}
        </div>
    </div>
    <div class="eventoDetailDiv">
        <div class="carousel slide"
             data-ride="carousel"
             id="evento-anexos-carousel">
            <div class="carousel-inner"></div>
            <a class="carousel-control-prev"
               href="#evento-anexos-carousel"
               role="button"
               data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">{% trans "Anterior" %}</span>
            </a>
            <a class="carousel-control-next"
               href="#evento-anexos-carousel"
               role="button"
               data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">{% trans "Próximo" %}</span>
            </a>
        </div>
        <ul class="list-group list-group-flush mt-4">
            {% if isTerritorial %}
                <li class="list-group-item bg-none px-0">
                    <dt>{% trans "Eventos" %}</dt>
                    <dd class="modal-right-title">
                    </dd>
                </li>
            {% endif %}
            <li class="list-group-item bg-none px-0 eventoDetailDivDimensao">
                <dt>{% trans "Dimensão" %}</dt>
                <dd id="evento-tipo">
                </dd>
            </li>
            {% if isTerritorial %}
                <li class="list-group-item bg-none px-0 eventoDetailDivSubDimensao">
                    <dt>Subdimensão</dt>
                    <dd id="evento-subdimensao">
                    </dd>
                </li>
            {% endif %}
            <li class="list-group-item bg-none px-0 eventoDetailDivPeriodo">
                <dt>
                    {% if isTerritorial %}
                        {% trans "Período" %}
                    {% else %}
                        {% trans "Ano" %}
                    {% endif %}
                </dt>
                <dd id="evento-ano">
                </dd>
            </li>
            <li class="list-group-item bg-none px-0 eventoDetailDivDescricao">
                <dt>{% trans "Descrição" %}</dt>
                <dd id="evento-descricao">
                </dd>
            </li>
        </ul>
    </div>
    <div class="eventoAnexosDiv{% if isTerritorial %} d-none{% endif %}">
        <div class="eventoAnexosDivInner">
            <h5>{% trans "Anexos" %}</h5>
            <div class="d-flex justify-content-end align-items-center">
                <a id="evento-anexos"
                   class="btn btn-primary btn-sm mr-1"
                   href=""
                   data-href="{% if isTerritorial %}{% url link_anexos pk=999999999999 %}{% else %}{% url 'linhadotempo:evento_anexos' agroecossistema_id=agroecossistema.id pk=999999999999 %}{% endif %}">
                    <i class="fas fa-pen mr-1"></i>
                    {% trans "Editar" %}
                </a>
            </div>
        </div>
        <div id="evento-anexos-files-wrapper" class="mt-3 mb-5">
            <ul class="list-group list-group-flush" id="evento-anexos-files">
                <li class="list-group-item"></li>
            </ul>
        </div>
        <div id="evento-anexos-files-empty" class="mt-3 mb-5">
            <span class="text-muted">{% trans "Este evento não tem arquivos anexos" %}</span>
        </div>
    </div>
{% endblock modal_right_body %}
{% block includes_footer %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
          rel="stylesheet" />
    <link rel="stylesheet"
          href="{% static 'linhadotempo/css/linhadotempo.css' %}">
{% endblock includes_footer %}

linhadotempo/templates/linhadotempo/eventogatilho_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load rules %}

{% block content %}
    {% has_perm 'permissao_padrao' user as pode_alterar %}
    <h3>{% trans "Evento-gatilho" %} <a href="{% url 'eventogatilho_list' %}" class="btn btn-secondary btn-sm"><i class="fas fa-eye mr-1"></i> {% trans "Ver lista" %}</a>
    </h3>
    <dl class="row mt-4">
      <dt class="col-sm-12 col-md-5 col-lg-3">{% trans "Organização" %}</dt>
          <dd class="col-sm-12 col-md-7 col-lg-9">{{ object.organizacao }}</dd>

          <dt class="col-sm-12 col-md-5 col-lg-3">{% trans "Título" %}</dt>
          <dd class="col-sm-12 col-md-7 col-lg-9">{{ object.titulo }}</dd>

          <dt class="col-sm-12 col-md-5 col-lg-3">{% trans "Dimensao" %}</dt>
          <dd class="col-sm-12 col-md-7 col-lg-9">{{ object.dimensao }}</dd>

          <dt class="col-sm-12 col-md-5 col-lg-3">{% trans "Criada em" %}</dt>
          <dd class="col-sm-12 col-md-7 col-lg-9">{{ object.criacao }}</dd>
    </dl>
    <div class="row mb-5">
        <div class="col-sm-12">
            <a class="btn btn-primary mt-2" href="{{ object.get_update_url }}"><i class="fas fa-pen mr-1"></i> {% trans 'Editar' %}</a>
        </div>
    </div>

{% endblock %}

linhadotempo/templates/linhadotempo/eventogrupo_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
    <p><a class="btn btn-primary btn-sm" href="{% url 'linhadotempo:eventogrupo_list' agroecossistema_id=agroecossistema.id %}">
        {% trans "Agrupamentos de Eventos" %}</a></p>
    <table class="table">
        <tr>
          <td>{% trans "Agrupamento" %}</td>
            <td>{{ object.name }}</td>
        </tr>
        <tr>
          <td>{% trans "Criado em" %}</td>
            <td>{{ object.criacao }}</td>
        </tr>
    </table>
    <a class="btn btn-primary" href="{{ object.get_update_url }}">{% trans "Editar Agrupamento" %}</a>

{% endblock %}