anexos/urls.py
from django.urls import path
from . import views

app_name = 'anexos'

urlpatterns = []

urlpatterns += (
    # path('pasta/', views.PastaListView.as_view(), name='pasta_anexo_list'),
    # path('pasta/create/', views.PastaCreateView.as_view(), name='pasta_anexo_create'),
    path('pasta/delete/<int:pk>/', views.PastaDeleteView.as_view(), name='pasta_anexo_delete'),
    # path('pasta/detail/<int:pk>/', views.PastaDetailView.as_view(), name='pasta_anexo_detail'),
    path('pasta/', views.PastaUpdateView.as_view(), name='pasta_anexo_update'),
)

urlpatterns += (
    path('', views.AnexoListView.as_view(), name='anexo_list'),
    path('filter/<str:filter>/', views.AnexoListView.as_view(), name='anexo_filter'),
    path('pasta/<int:pastaId>/', views.AnexoListView.as_view(), name='anexo_pasta'),
    path('create/', views.AnexoCreateView.as_view(), name='anexo_create'),
    path('detail/<int:pk>/', views.AnexoDetailView.as_view(), name='anexo_detail'),
    path('update/<int:pk>/', views.AnexoUpdateView.as_view(), name='anexo_update'),
    path('rest/update/', views.AnexoRestUpdateView.as_view(), name="anexo_rest_update"),
    path('delete/ajax/<int:pk>/', views.AnexoDeleteAjaxView.as_view(), name='anexo_delete_ajax'),
    path('delete/<int:pk>/', views.AnexoDeleteView.as_view(), name='anexo_delete'),
)

urlpatterns += (
    # urls for AnexoRecipiente
    path('<int:related_type>/<int:related_id>', views.AnexoRecipienteListView.as_view(), name='anexorecipiente_list'),
    path('<int:related_type>/<int:related_id>/create/', views.AnexoRecipienteCreateView.as_view(), name='anexorecipiente_create'),
    path('<int:related_type>/<int:related_id>/detail/<int:pk>/', views.AnexoRecipienteDetailView.as_view(),
         name='anexorecipiente_detail'),
    path('<int:related_type>/<int:related_id>/update/<int:pk>/', views.AnexoRecipienteUpdateView.as_view(),
         name='anexorecipiente_update'),
    path('<int:related_type>/<int:related_id>/delete/<int:pk>/', views.AnexoRecipienteDeleteView.as_view(),
         name='anexorecipiente_delete'),
)

lume/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('markdown/', include('django_markdown.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    # path('anexos/', include('anexos.urls')),
    url(r'^municipios_app/', include('municipios.urls')),
    path('paises_municipios/', include('paises_municipios.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('analiseagregada/', include('analiseagregada.urls')),
    path('linhaterritorial/', include('linhaterritorial.urls')),
    path('conjunto_organizacoes/', include('conjunto_organizacoes.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
]

urlpatterns += [
    path('agroecossistema/', include('agroecossistema.urls_main')),
    path('agroecossistema/<int:agroecossistema_id>/',
         include('agroecossistema.urls')),
    path('<int:agroecossistema_id>/car/<int:ano_car>/economica/',
         include('economica.urls', namespace='economica')),
    path('<int:agroecossistema_id>/car/<int:ano_car>/simulacao/<str:sim_slug>/economica/',
         include('economica.urls', namespace='ecosim')),
    path('<int:agroecossistema_id>/linhadotempo/', include('linhadotempo.urls')),
    path('<int:agroecossistema_id>/cadernodecampo/',
         include('cadernodecampo.urls')),
    path('<int:agroecossistema_id>/qualitativa/', include('qualitativa.urls')),
    path('<int:agroecossistema_id>/anexos/', include('anexos.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog')
]

urlpatterns += staticfiles_urlpatterns()
if settings.LOCAL:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

anexos/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from django.urls import reverse
from django.utils.translation import gettext as _
from multiupload.fields import MultiFileField

from main.forms import LumeModelForm, LumeForm
from .models import PastaAnexo, Anexo, AnexoRecipiente
from agroecossistema.models import Agroecossistema


class PastaForm(LumeModelForm):

    def __init__(self, *args, **kwargs):
        self.can_delete = kwargs.pop('can_delete', False)

        if self.can_delete:
            agroecossistema_id = kwargs.pop('agroecossistema_id')
            self.delete_confirm_message = _('Deseja realmente apagar esta pasta?')
            self.delete_url = reverse('anexos:pasta_anexo_delete', kwargs={'agroecossistema_id': agroecossistema_id, 'pk': kwargs.get('instance').id})
            self.delete_success_url = reverse('anexos:pasta_anexo_update', kwargs={'agroecossistema_id': agroecossistema_id})
        super(PastaForm, self).__init__(*args, **kwargs)

    class Meta:
        model = PastaAnexo
        fields = ['nome']
        # labels = {
        #     'mae': _('Pasta mãe')
        # }

PastaFormSet = inlineformset_factory(
    Agroecossistema,
    PastaAnexo,
    form=PastaForm,
    can_delete=True,
    extra=1,
    min_num=0
)


class AnexoForm(LumeModelForm):

    def __init__(self, agroecossistema_id = None, *args, **kwargs):
        self.can_delete = kwargs.pop('can_delete', False)
        if self.can_delete:
            self.delete_confirm_message = _('Deseja realmente apagar este arquivo?')
            # self.delete_url = reverse('anexos:anexo_delete_ajax', kwargs={'agroecossistema_id': agroecossistema.id, 'pk': kwargs.get('instance').id})
            # self.delete_success_url = reverse('anexos:anexo_list', kwargs={'agroecossistema_id': agroecossistema.id})

        super(AnexoForm, self).__init__(*args, **kwargs)

        if agroecossistema_id:
            self.fields['pasta'].queryset = PastaAnexo.objects.filter(agroecossistema_id=agroecossistema_id)

    class Meta:
        model = Anexo
        fields = ['arquivo', 'nome', 'descricao', 'pasta']

class AnexoRestForm(LumeModelForm):
    class Meta:
        model = Anexo
        fields = []

class AnexoRecipienteForm(LumeForm):
    arquivos = MultiFileField(min_num=0, required=True)
    descricao = forms.CharField(widget=forms.Textarea, required=False)


class AnexoRecipienteForm(LumeModelForm):
    class Meta:
        model = AnexoRecipiente
        fields = []

anexos/views.py
import os

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from django.views.generic.edit import DeleteView, FormView, FormMixin

from django.utils.translation import gettext as _
from rules.contrib.views import PermissionRequiredMixin

from anexos.mixins import AjaxableResponseMixin
from anexos.utils import organiza_anexos
from cadernodecampo.models import Anotacao
from linhadotempo.models import Evento
from agroecossistema.models import Agroecossistema
from agroecossistema.forms import AgroecossistemaForm
from main.views import LumeDeleteView
from .forms import PastaForm, PastaFormSet, AnexoForm, AnexoRestForm, AnexoRecipienteForm, AnexoRecipienteForm
from .models import PastaAnexo, Anexo, AnexoRecipiente


class PastaListView(ListView):
    model = PastaAnexo


class PastaCreateView(CreateView):
    model = PastaAnexo
    form_class = PastaForm


class PastaDetailView(DetailView):
    model = PastaAnexo


class PastaUpdateView(PermissionRequiredMixin, UpdateView):
    model = Agroecossistema
    form_class = AgroecossistemaForm
    permission_required = 'permissao_padrao'
    titulo = _('Editar Pasta')
    template_name = 'anexos/pasta_form.html'

    def get_permission_object(self):
        agroecossistema = get_object_or_404(Agroecossistema, id=self.kwargs['agroecossistema_id'])
        return agroecossistema

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = self.titulo
        context['modulo'] = 'anexos'
        context['submodulo'] = 'pastas'
        context['agroecossistema'] = Agroecossistema.objects.get(id=self.kwargs['agroecossistema_id'])
        if self.request.POST:
            context['pastas_formset'] = PastaFormSet(self.request.POST, instance=self.get_object())
        else:
            context['pastas_formset'] = PastaFormSet(instance=self.get_object())

        return context

    def get_form_kwargs(self):
        kwargs = super(PastaUpdateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        kwargs.update({'can_delete': self.request.user.has_perm('agroecossistema.apagar', self.get_object())})
        return kwargs

    def form_valid(self, form):
        context = self.get_context_data()
        pastas_formset = context['pastas_formset']

        try:
            with transaction.atomic():
                self.object = form.save()

                if pastas_formset.is_valid():
                    pastas_formset.instance = self.object
                    pastas_formset.save()
                else:
                    tmp = form.full_clean()
                    form._errors[NON_FIELD_ERRORS] = form.error_class([
                        _("Foram encontrados erros no formulário e os dados NÃO foram salvos. Favor fazer as correções indicadas.")
                    ])
                    return self.render_to_response(self.get_context_data(form=form))

        except ValueError:
            tmp = form.full_clean()
            form._errors[NON_FIELD_ERRORS] = form.error_class([
                _("Foram encontrados erros no formulário e os dados NÃO foram salvos. Favor fazer as correções indicadas.")
            ])
            return self.render_to_response(self.get_context_data(form=form))

        return super(PastaUpdateView, self).form_valid(form)

    def get_object(self, queryset=None):
        return Agroecossistema.objects.get(pk=self.kwargs['agroecossistema_id'])

    def get_success_url(self, object_id=None):
        return reverse('anexos:pasta_anexo_update', kwargs={'agroecossistema_id': self.kwargs['agroecossistema_id']})


class PastaDeleteView(PermissionRequiredMixin, LumeDeleteView):
    model = PastaAnexo
    permission_required = 'agroecossistema.alterar'

    def get_permission_object(self):
        agroecossistema = get_object_or_404(Agroecossistema, id=self.kwargs['agroecossistema_id'])
        return agroecossistema

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(PastaDeleteView, self).dispatch(*args, **kwargs)


class AnexoListView(FormMixin, ListView):
    model = Anexo
    template_name = 'anexos/anexo_list.html'
    form_class = AnexoForm

    def get_form_kwargs(self):
        kwargs = super(AnexoListView, self).get_form_kwargs()
        kwargs.update({
            'can_delete': self.request.user.has_perm('permissao_padrao')
        })
        if 'agroecossistema_id' in self.kwargs:
            kwargs['agroecossistema_id'] = self.kwargs['agroecossistema_id']
        if 'data' in kwargs and 'update_pk' in kwargs['data'] and kwargs['data']['update_pk'] != '':
            kwargs['instance'] = Anexo.objects.get(pk=int(kwargs['data']['update_pk']))

        return kwargs

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        anexo = form.save(commit=False)

        anexo.agroecossistema=Agroecossistema.objects.get(pk=self.kwargs['agroecossistema_id'])

        arquivo = form.cleaned_data['arquivo']
        if arquivo.__class__.__name__ == 'InMemoryUploadedFile':
            anexo.mimetype = arquivo.content_type
            if anexo.nome is None or anexo.nome == "":
                anexo.nome = os.path.splitext(arquivo.name)[0]

        anexo.save()

        if 'related_type' in self.kwargs:
            related_type = ContentType.objects.get(app_label=self.kwargs['related_type'], model=self.kwargs['related_model'].lower())
            anexo_recipiente, created = AnexoRecipiente.objects.get_or_create(
                recipiente_object_id=self.kwargs['pk'],
                anexo_id=anexo.id,
                recipiente_content_type_id=related_type.id
            )
            return HttpResponseRedirect(reverse(
                f"{self.kwargs['related_type']}:{self.kwargs['related_model'].lower()}_anexos",
                args=(self.kwargs['agroecossistema_id'],self.kwargs['pk'],)
            ))

        return HttpResponseRedirect(
            reverse('anexos:anexo_list', args=(self.kwargs['agroecossistema_id'],))
        )

    def get_queryset(self):
        relatedType = None
        if 'related_type' in self.kwargs:
            relatedType = self.kwargs['related_type']

        if not relatedType:
            contentType = ContentType.objects.get(app_label='agroecossistema', model='agroecossistema')
            if 'filter' in self.kwargs:
                filter = self.kwargs['filter']
                anexosAll = Anexo.objects.filter(agroecossistema_id=self.kwargs['agroecossistema_id']).order_by('-ultima_alteracao')
                anexos = []
                for anexo in anexosAll:
                    if filter == 'imagens':
                        if anexo.is_image():
                            anexos.append(anexo)
                        continue

                    if filter == 'videos':
                        if anexo.is_video():
                            anexos.append(anexo)
                        continue

                    if not anexo.is_video() and not anexo.is_image():
                        anexos.append(anexo)

            elif 'pastaId' in self.kwargs:
                pastaId = self.kwargs['pastaId']
                anexos = Anexo.objects.filter(agroecossistema_id=self.kwargs['agroecossistema_id'], pasta_id=pastaId).order_by('-ultima_alteracao')

            else:
                anexos = Anexo.objects.filter(agroecossistema_id=self.kwargs['agroecossistema_id']).order_by('-ultima_alteracao')

            return anexos

        # is related content!
        anexosRecipientesList = AnexoRecipiente.objects.filter(recipiente_object_id=self.kwargs['pk']).order_by('-ultima_alteracao').values_list('anexo_id')
        return Anexo.objects.filter(pk__in=anexosRecipientesList)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        relatedType = None
        if 'related_type' in self.kwargs:
            relatedType = self.kwargs['related_type']
        comPastas = True

        if 'agroecossistema_id' in self.kwargs:
            context['agroecossistema'] = Agroecossistema.objects.get(id=self.kwargs['agroecossistema_id'])
        context['modo'] = 'grade' if not ('modo' in self.request.GET) else self.request.GET['modo']
        context['modulo'] = relatedType if relatedType else 'anexos'
        context['isPasta'] = False
        context['titulo'] = _('Anexos')
        context['anexosPlural'] = _('arquivos')
        context['anexosSingular'] = _('arquivo')

        if not relatedType:
            context['submodulo'] = 'todos'
            context['anexosUrlList'] = reverse("anexos:anexo_list", args=(self.kwargs['agroecossistema_id'],))
            context['anexosUrlCreate'] = reverse("anexos:anexo_create", args=(self.kwargs['agroecossistema_id'],))
            if 'filter' in self.kwargs:
                filter = self.kwargs['filter']
                context['submodulo'] = filter
                if filter == 'imagens':
                    context['titulo'] = _("Imagens")
                    context['anexosPlural'] = _("imagens")
                    context['anexosSingular'] = _("imagem")
                elif filter == 'videos':
                    context['titulo'] = _("Vídeos")
                    context['anexosPlural'] = _("vídeos")
                    context['anexosSingular'] = _("vídeo")
                elif filter == 'documentos':

anexos/templates/anexos/anexo_detail.html
{% extends "base.html" %}
{% load vstatic %}
{% load i18n %}
{% load rules %}
{% load anexos %}
{% block includes %}
    <link rel="stylesheet" href="{% vstatic 'anexos/css/anexos.css' %}">
    <style>
      .anexo-image {
        height: unset;
      }
    </style>
{% endblock %}
{% block breadcrumb_bar %}{% endblock %}
{% block content %}
    {% has_perm 'permissao_padrao' user as pode_alterar %}
    <div class="row mt-4 text-left">
        <div class="col-lg-3 col-md-4 col-12">
            <figure class="figure w-100">
                <div class="thumbnail">{{ object.thumbnail_tag|safe }}</div>
            </figure>
        </div>
        <div class="col-lg-9 col-md-8 col-12">
            <h3>
                <a href="{{ object.arquivo.url }}" target="_blank">{{ object.nome }}</a>
            </h3>
            <!--h5>Tipo: {{ object.tipo.nome }}</h5 -->
            <p>{{ object.descricao|linebreaks }}</p>
        </div>
    </div>
    {% if pode_alterar %}
        <div class="row mb-5 mt-4">
            <div class="col-sm-12">
                <a class="btn btn-primary mt-2"
                   href="{% url 'anexos:anexo_update' agroecossistema_id=agroecossistema.id pk=object.id %}"><i class="fas fa-pen mr-1"></i> {% trans 'Editar' %}</a>
            </div>
        </div>
    {% endif %}
    {# <hr>
    <h3>Objetos associados:</h3>
    <ul>
        {% for anexorecipiente in object.recipientes.all %}
            <li>
                {{anexorecipiente.recipiente}}
                <a href="{% url 'anexos:anexorecipiente_list' related_type=anexorecipiente.recipiente_content_type_id related_id=anexorecipiente.recipiente_object_id %}">{{ anexorecipiente.recipiente|get_class }}: {{ anexorecipiente.recipiente }}</a>
            </li>
        {% endfor %}
</ul> #}
{% endblock %}

anexos/templates/anexos/anexo_e_recipiente_form.html
{% extends "base.html" %}
{% load static %}
{% load anexos %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>{{ titulo }}</h1>
    {% crispy form %}
{% endblock %}

anexos/templates/anexos/anexo_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load anexos %}

{% block content %}
<h3>
    {% if submodulo == 'update' %}
        {{ titulo }}: <strong>{{ object.nome }}</strong>
    {% else %}
        {{ titulo }}
    {% endif %}
</h3>

<div class="row mt-5">
    <div class="col-md-12">
        {% crispy form %}
    </div>
</div>

{% endblock %}

anexos/templates/anexos/anexo_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load vstatic %}
{% load i18n %}
{% load l10n %}
{% load custom_tags %}
{% load anexos %}
{% load anexos_tags %}

{% block includes %}
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
    <link rel="stylesheet" href="{% vstatic 'anexos/css/anexos.css' %}">
    <script type="text/javascript" src="{% vstatic 'anexos/js/anexos.js' %}"></script>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}

    <div id="maskArmengue" ondragover = "armengue(event)"></div>

    <div class="mt-3 d-flex justify-content-between align-items-center">
        <h3>
            {{ titulo }}
            {% if isPasta %}
                <small class="qtdeAnexos">
                    ({% if anexos.soltos|length == 1 %}1 {{ anexosSingular }}{%else%}{{ anexos.soltos|length }} {{ anexosPlural }}{% endif %})
                </small>
            {% else %}
                <small class="text-muted ml-2">
                    ({% trans 'arraste para mudar pasta' %})
                </small>
            {% endif %}
        </h3>
        <div class="d-flex justify-content-end align-items-center">
            {% if modo == 'lista' %}
                <a
                    id="btnGrade"
                    class="btn btn-secondary btn-sm btn-toggle-modo mr-2"
                    href="{{ anexosUrlList }}?modo=galeria"
                >
                    <i class="fas fa-image mr-1"></i>
                    {% trans "Galeria" %}
                </a>
            {% else %}
                <a
                    id="btnLista"
                    class="btn btn-secondary btn-sm btn-toggle-modo mr-2"
                    href="{{ anexosUrlList }}?modo=lista"
                >
                    <i class="fas fa-list mr-1"></i>
                    {% trans "Lista" %}
                </a>
            {% endif %}
            <button
                id="btn-criar"
                class="btn btn-primary btn-sm modal-right-open"
            >
                <i class="fas fa-plus mr-1"></i>
                {% trans "Novo anexo" %}
            </button>
            {% if related_id %}
                <a
                    id="btnVoltar"
                    class="btn btn-primary btn-sm ml-2"
                    href="{{ relatedUrl }}"
                >
                    <i class="fas fa-arrow-left mr-1"></i>
                    {% trans "Voltar" %}
                </a>
            {% endif %}
        </div>
    </div>

    {% if modo == 'lista' %}
        {% anexosModoLista agroecossistema=agroecossistema anexos=anexos isPasta=isPasta titulo=titulo anexosSingular=anexosSingular anexosPlural=anexosPlural related_id=related_id %}
    {% else %}
        {% anexosModoGrade agroecossistema=agroecossistema anexos=anexos isPasta=isPasta anexosSingular=anexosSingular anexosPlural=anexosPlural %}
    {% endif %}

    <div
        id="anexoModal"
        class="modal fade bd-example-modal-lg"
        tabindex="-1"
        role="dialog"
        aria-labelledby="myLargeModalLabel"
        aria-hidden="true"
    >
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
            </div>
        </div>
    </div>


    {% if 1 == 2 %}
        <div class="col-md-12 mt-2">
            <div class="alert alert-dark">
                <h5>
                    Não há {{ anexosPlural }}
                </h5>
            </div>
        </div>
    {% endif %}

{% else %}
    <script>
        window.location='/';
    </script>
{% endif %}

{% endblock %}

{% block modal_right_form_tag %}
    {% if form %}
        <form method="post" class="h-100 form-vertical" enctype="multipart/form-data">
    {% endif %}
{% endblock %}

{% block modal_right_title %}
    <h3 id="modal-right-title" class="mb-2" data-title_criar="{% trans 'Novo anexo' %}" data-title_editar="{% trans 'Editar anexo' %}">{% trans 'Novo anexo' %}</h3>
{% endblock %}

{% block modal_right_body %}
    <div>
        {% csrf_token %}
        <div id="id_arquivo_img">
            <div class="img-thumb"></div>
            <div class="img-label"></div>
            <button class="btn btn-sm btn-secondary">{% trans 'Trocar arquivo' %}</button>
        </div>
        {{ form|crispy }}
        <input type="hidden" id="id_update_pk" name="update_pk" value="">
    </div>
{% endblock %}

anexos/templates/anexos/anexorecipiente_detail.html
{% extends "base.html" %}
{% load static %}
{% load anexos %}
{% block content %}
    <p><a class="btn btn-primary btn-sm" href="{% url 'anexorecipiente_list' related_type=related_type related_id=related_id %}">
        {% trans "Anexo" %}</a></p>
    <table class="table">
        <tr>
          <td>{% trans "anexo" %}</td>
            <td>{{ object.recipiente_object_id }}</td>
        </tr>
    </table>
    <a class="btn btn-primary" href="{{ object.get_update_url }}">{% trans "Editar anexo" %}</a>

{% endblock %}

anexos/templates/anexos/anexorecipiente_form.html
{% extends "base.html" %}
{% load static %}
{% load anexos %}
{% load crispy_forms_tags %}
{% block content %}
    <h3>Anexos</h3>
    {% crispy form %}
{% endblock %}

anexos/templates/anexos/anexorecipiente_list.html
{% extends "base.html" %}
{% load vstatic %}
{% load i18n %}
{% load anexos %}

{% block includes %}
    <link rel="stylesheet" href="{% vstatic 'anexos/css/anexos.css' %}">
    <script type="text/javascript" src="{% vstatic 'anexos/js/anexos.js' %}"></script>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h3>{% trans "Anexos" %} - {{ related_object|get_class|lower }} <i>{{ related_object }}</i> <a class="btn btn-success btn-sm"
       href="{% url 'anexos:anexorecipiente_create' related_type=related_type related_id=related_id %}">
    <i class="fas fa-plus"></i> {% trans "Novo anexo" %}</a></h3>
    <div class="row text-center text-lg-left">
        {% if object_list|length > 0 %}
        {% for object in object_list %}
            <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12 arquivo">
                <figure class="figure w-100">
                    <div class="thumbnail">
                        <div class="caption">
                            <p class="caption-apagar" data-url="{{ object.anexo.get_delete_ajax_url }}" data-filename="{{ object.anexo.nome }}"><i class="fas fa-trash"></i></p>
                            <p class="caption-descricao">{{ object.anexo.descricao }}</p>
                            <p><a href="{{ object.anexo.get_absolute_url }}" class="btn btn-info btn-xs">{% trans "Detalhes" %}</a> <a href="{{ object.anexo.arquivo.url }}" class="btn btn-light btn-xs" target="_blank">{% trans "Baixar" %}</a></p>
                        </div>
                        {{ object.anexo.thumbnail_tag|safe }}
                    </div>
                    <figcaption class="figure-caption">{{ object.anexo.nome }}</figcaption>
                </figure>

            </div>
        {% endfor %}
        {% else %}
            <div class="col-md-12 mt-2">
                <div class="alert alert-dark">
                  <h5>{% trans "Ainda não há anexos. Seja a/o primeira/o a anexar um arquivo" %}<a href="{% url 'anexos:anexorecipiente_create' related_type=related_type related_id=related_id %}">{% trans "anexar um arquivo" %}</a>.</h5>
                </div>
            </div>
        {% endif %}
    </div>

    <a class="btn btn-primary" href="{{ related_object.get_absolute_url }}">
      <i class="fas fa-arrow-left"></i> {% blocktrans %}Voltar a <i>{{ related_object }}{% endblocktrans %}</i></a>

{% else %}
<script>
window.location='/';
</script>
{% endif %}
{% endblock %}

anexos/templates/anexos/janela_anexos.html
Janela Anexos

anexos/templates/anexos/pasta_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load rules %}

{% block content %}
<h3>{% trans "Tipo" %} <a href="{% url 'tipo_anexos:anexo_list' %}" class="btn btn-secondary btn-sm">
    <i class="fas fa-eye mr-1"></i> {% trans "Ver lista de tipos" %}</a>
    </h3>
    <dl class="row mt-4">
      <dt class="col-sm-12 col-md-5 col-lg-3">{% trans "Nome" %}</dt>
          <dd class="col-sm-12 col-md-7 col-lg-9">{{ object.nome }}</dd>
    </dl>
    {% if pode_alterar %}
        <div class="row mb-5">
            <div class="col-sm-12">
              <a class="btn btn-primary mt-2" href="{{ object.get_update_url }}"><i class="fas fa-pen mr-1"></i> {% trans "Editar" %}</a>
            </div>
        </div>
    {% endif %}

{% endblock %}

anexos/templates/anexos/tag_anexos_docs.html
{% for anexo in anexos %}
    {{ anexo.nome }}<br/>
{% endfor %}

anexos/templates/anexos/tag_anexos_slider.html
{% for anexo in anexos %}
    {{ anexo.nome }}<br/>
{% endfor %}